In [ ]:
# Install libraries

# !pip install tensorflow
# !pip install pydot
# !pip install graphviz


In [3]:
import tensorflow as tf
import numpy as np


tf.debugging.set_log_device_placement(True)

tf.executing_eagerly()

True

In [4]:
x = tf.constant(3)
x

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [18]:
v1 = tf.Variable([1, 2, 3,4])
v2 = tf.Variable([1, 2, 3,4])
tf.add(v1, v2)

v1.assign_add([7, 7, 7, 7])
print(v1)
v1.numpy()

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assig

array([ 8,  9, 10, 11])

In [19]:
result = x + 5
print(result)

x1 = tf.constant([1.1, 1.2, 1.3, 1.4])
x1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(8, shape=(), dtype=int32)
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 1.2, 1.3, 1.4], dtype=float32)>