In [1]:
import tensorflow as tf

tf.compat.v2.executing_eagerly()

True

In [4]:
a = tf.constant(5, name="a")
a + 1

In [7]:
x = [[10.0]]
res = tf.matmul(x, x)
res

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[100.]], dtype=float32)>

In [10]:
a = tf.constant([[10, 20],
                 [30, 40]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [15]:
b = tf.add(a, 5)
print(b)

a * b

tf.Tensor(
[[15 25]
 [35 45]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 150,  500],
       [1050, 1800]])>

In [22]:
m = tf.Variable(4, 5, 6, name="m")
c = tf.Variable(10, 20, 30, name="c")

x = tf.Variable([100, 200, 300], name="x")
x

<tf.Variable 'x:0' shape=(3,) dtype=int32, numpy=array([100, 200, 300])>

In [23]:
y = m * x + c
y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 410,  810, 1210])>

In [24]:
import time
import warnings
import logging
import tensorflow as tf

In [27]:
@tf.function
def add(a, b):
    return a + b

add(3, 4)

<tf.Tensor: shape=(), dtype=int32, numpy=7>