In [1]:
import tensorflow as tf

tf.compat.v2.executing_eagerly()

True

In [4]:
a = tf.constant(5, name="a")
a + 1

In [7]:
x = [[10.0]]
res = tf.matmul(x, x)
res

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[100.]], dtype=float32)>

In [10]:
a = tf.constant([[10, 20],
                 [30, 40]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [15]:
b = tf.add(a, 5)
print(b)

a * b

tf.Tensor(
[[15 25]
 [35 45]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 150,  500],
       [1050, 1800]])>

In [22]:
m = tf.Variable(4, 5, 6, name="m")
c = tf.Variable(10, 20, 30, name="c")

x = tf.Variable([100, 200, 300], name="x")
x

<tf.Variable 'x:0' shape=(3,) dtype=int32, numpy=array([100, 200, 300])>

In [23]:
y = m * x + c
y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 410,  810, 1210])>

In [24]:
import time
import warnings
import logging
import tensorflow as tf

In [27]:
@tf.function
def add(a, b):
    return a + b

add(3, 4)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [29]:
num = tf.Variable(7)

In [33]:
@tf.function
def add_times(x):
    for i in tf.range(x):
        num.assign_add(x)

In [34]:
add_times(5)
num

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>

In [46]:
@tf.function
def square(x):
    print("Input: ", x)
    tf.print("Graph print:", x)
    return x * x

In [48]:
square(x)

Graph print: [100 200 300]


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10000, 40000, 90000])>

In [49]:
square(1000)

Input:  1000
Graph print: 1000


<tf.Tensor: shape=(), dtype=int32, numpy=1000000>

In [58]:
@tf.function
def time_compute(x):
    return x

start = time.time()
for i in tf.range(2000):
    time_compute(i)

end = time.time()

print("tf.tensor time elapsed: ", end-start)

tf.tensor time elapsed:  1.5617938041687012


In [52]:
warnings.filterwarnings('ignore')
logging.getLogger("tensforflow").disabled = True

In [ ]:
start = time.time()
for i in range(2001):
    time_compute(i)

end = time.time()
print("tf.tensor time elapsed: ", end-start)