In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [8]:
x = tf.Variable(4.0)
with tf.GradientTape() as tape:
    y = x**2

y

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [9]:
dy_x = tape.gradient(y, x)
dy_x

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [10]:
w = tf.Variable(tf.random.normal((4,2)))
w

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[ 1.5172198 ,  0.5414564 ],
       [-0.45720205,  0.6250777 ],
       [ 0.67868537, -0.48597702],
       [-1.4216726 ,  0.2934728 ]], dtype=float32)>

In [11]:
b = tf.Variable(tf.ones(2))
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [12]:
x = tf.Variable([[10., 20., 30, 40]])
x

<tf.Variable 'Variable:0' shape=(1, 4) dtype=float32, numpy=array([[10., 20., 30., 40.]], dtype=float32)>

In [13]:
with tf.GradientTape(persistent=True) as tape:
    y = tf.matmul(x, w) + b
    loss = tf. reduce_mean(y**2)

In [14]:
[dl_dw, dl_db] = tape.gradient(loss, [w,b])
dl_dw

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ -294.78186,   160.7572 ],
       [ -589.5637 ,   321.5144 ],
       [ -884.34564,   482.2716 ],
       [-1179.1274 ,   643.0288 ]], dtype=float32)>

In [16]:
dl_db

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-29.478188,  16.07572 ], dtype=float32)>

In [19]:
layer = tf.keras.layers.Dense(2, activation='relu')
x = tf.constant([[10, 20, 30]])

In [20]:
with tf.GradientTape() as tape:
    y = layer(x)
    loss = tf.reduce_sum(y**2)

grad = tape.gradient(loss, layer.trainable_variables)

In [21]:
grad

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 157.64368,  517.11255],
        [ 315.28735, 1034.2251 ],
        [ 472.93103, 1551.3378 ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([15.764368, 51.711258], dtype=float32)>]

In [23]:
x.shape, y.shape


(TensorShape([1, 3]), TensorShape([1, 2]))